# Generated by Django 4.2.5 on 2023-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0002_category_alter_serie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='category',
            field=models.ManyToManyField(to='suivi.category'),
        ),
    ]
